//Roles y usuario admin
INSERT INTO roles (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO roles (ROLE) VALUES ('ROLE_SUPER');
INSERT INTO roles (ROLE) VALUES ('ROLE_SPRAY');
INSERT INTO roles (ROLE) VALUES ('ROLE_CENSUS');
INSERT INTO roles (ROLE) VALUES ('ROLE_REVIEW');
INSERT INTO roles (ROLE) VALUES ('ROLE_PASSWORD');
INSERT INTO users (username, credentialsNonExpired, accountNonLocked, changePasswordNextLogin, completeName, created,createdBy, accountNonExpired, email, enabled, lastAccess, lastCredentialChange, modified, modifiedBy, password) VALUES ('admin', b'1', b'1', b'0', 'Administrador del Sistema', '2018-11-08 00:00:00', 'admin', b'1', 'waviles@clintonhealthaccess.org', b'1', '2018-11-08 00:00:00', '2018-11-08 00:00:00', '2018-11-08 00:00:00', 'admin', '6c36dc262b0e44be5811c2296669fc65643aec9dcaa4a76501e0a9508b633fd01ee59a207f8c6d68');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_ADMIN', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_PASSWORD', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_SPRAY', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_CENSUS', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_SUPER', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');
INSERT INTO userroles (ROLE, username, deviceid, status, pasive, recordDate,recordUser) VALUES ('ROLE_REVIEW', 'admin', 'admin', '2', '0', '2018-11-08 00:00:00', 'admin');


INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('access', NULL, NULL, 'User access', '0', 0, '0', 'Accesos de usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('actions', NULL, NULL, 'Actions', '0', 0, '0', 'Acciones');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('active', NULL, NULL, 'Active', '0', 0, '0', 'Activo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('add', NULL, NULL, 'Add', '0', 0, '0', 'Agregar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('addedBy', NULL, NULL, 'Added by', '0', 0, '0', 'Agregado por');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('admin', NULL, NULL, 'Administration', '0', 0, '0', 'Administración');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('all', NULL, NULL, 'All', '0', 0, '0', 'Todos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ask.chgpass', NULL, NULL, 'Demand password change', '0', 0, '0', 'Exigir cambio de contraseña');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('audittrail', NULL, NULL, 'Audit Trail', '0', 0, '0', 'Bitacora de cambios');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('back', NULL, NULL, 'Return/back', '0', 0, '0', 'Regresar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('backLogin', NULL, NULL, 'Return to login page', '0', 0, '0', 'Regresar a página de ingreso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('cancel', NULL, NULL, 'Cancel', '0', 0, '0', 'Cancelar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('category', NULL, NULL, 'Category', '0', 0, '0', 'Categoría');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('catKey', NULL, NULL, 'Response value', '0', 0, '0', 'Valor de la respuesta');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('catRoot', NULL, NULL, 'Root catalogue', '0', 0, '0', 'Catálogo Padre');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('change', NULL, NULL, 'Change', '0', 0, '0', 'Cambiar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('changepass', NULL, NULL, 'Change password', '0', 0, '0', 'Cambiar contraseña..');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('choose', NULL, NULL, 'Choose', '0', 0, '0', 'Elegir');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.users.model.Authority', NULL, NULL, 'Role', '0', 0, '0', 'Rol de Usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.users.model.UserSistema', NULL, NULL, 'User', '0', 0, '0', 'Usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('confirm', NULL, NULL, 'Confirm', '0', 0, '0', 'Confirmar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('createdBy', NULL, NULL, 'Created by', '0', 0, '0', 'Creado por');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('credentials.expired', NULL, NULL, 'Your password has expired', '0', 0, '0', 'Su contraseña ha caducado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('dateAdded', NULL, NULL, 'Date', '0', 0, '0', 'Fecha');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('dateCreated', NULL, NULL, 'Date created', '0', 0, '0', 'Fecha creacion');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('dateCredentials', NULL, NULL, 'Last change of password', '0', 0, '0', 'Ultimo cambio de contrasena');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('dateModified', NULL, NULL, 'Date of modification', '0', 0, '0', 'Fecha de modificación');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('delete', NULL, NULL, 'Delete', '0', 0, '0', 'Eliminar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('denied', NULL, NULL, 'Access denied', '0', 0, '0', 'Acceso denegado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('deniedmessage', NULL, NULL, 'Sorry, the page you\'re looking for isn\'t available with your credentials', '0', 0, '0', 'Lo sentimos, la página que solicitó no esta disponible con sus credenciales.');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('disable', NULL, NULL, 'Disable', '0', 0, '0', 'Deshabilitar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('edit', NULL, NULL, 'Edit', '0', 0, '0', 'Editar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('empty', NULL, NULL, 'Blank', '0', 0, '0', 'En blanco');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('enable', NULL, NULL, 'Enable', '0', 0, '0', 'Habilitar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('enabled', NULL, NULL, 'Enabled', '0', 0, '0', 'Habilitado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('disabled', NULL, NULL, 'Disabled', '0', 0, '0', 'Deshabilitado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('end', NULL, NULL, 'End', '0', 0, '0', 'Finalizar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('english', NULL, NULL, 'English', '0', 0, '0', 'Inglés');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('entityClass', NULL, NULL, 'Class', '0', 0, '0', 'Clase');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('entityName', NULL, NULL, 'Name', '0', 0, '0', 'Nombre');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('entityProperty', NULL, NULL, 'Property', '0', 0, '0', 'Propiedad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('entityPropertyNewValue', NULL, NULL, 'New value', '0', 0, '0', 'Nuevo valor');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('entityPropertyOldValue', NULL, NULL, 'Old value', '0', 0, '0', 'Valor anterior');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('expiredToken', NULL, NULL, 'The token has expired', '0', 0, '0', 'El token ha expirado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('export', NULL, NULL, 'Export', '0', 0, '0', 'Exportar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('footer', NULL, NULL, '2019 MSPAS', '0', 0, '0', '2019 MSPAS');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('generate', NULL, NULL, 'Generate', '0', 0, '0', 'Generar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('heading', NULL, NULL, 'Vector Control Activities', '0', 0, '0', 'Actividades de control de vectores');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('home', NULL, NULL, 'Start', '0', 0, '0', 'Inicio');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('invalidToken', NULL, NULL, 'The token is invalid', '0', 0, '0', 'El token es inválido');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ipaddress', NULL, NULL, 'IP address', '0', 0, '0', 'Direccion IP');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('language', NULL, NULL, 'Language', '0', 0, '0', 'Idioma/Language');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('lastAccess', NULL, NULL, 'Last access', '0', 0, '0', 'Ultimo acceso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('lock', NULL, NULL, 'Lock', '0', 0, '0', 'Bloquear');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('locked', NULL, NULL, 'Locked', '0', 0, '0', 'Bloqueado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login', NULL, NULL, 'Login', '0', 0, '0', 'Ingresar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.accountExpired', NULL, NULL, 'User account has expired', '0', 0, '0', 'Cuenta de usuario ha expirado!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.accountLocked', NULL, NULL, 'User account is locked', '0', 0, '0', 'Cuenta de usuario está bloqueada!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.accountNotLocked', NULL, NULL, 'User account is not locked', '0', 0, '0', 'Cuenta de usuario está desbloqueada!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.badCredentials', NULL, NULL, 'User name or password is incorred', '0', 0, '0', 'Nombre de usuario o contraseña incorrectos!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.credentialsExpired', NULL, NULL, 'User credentials have expired', '0', 0, '0', 'Credenciales de usuario han expirado!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.forgot.password', NULL, NULL, 'Forgot password?', '0', 0, '0', 'Olvidó contraseña?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.maxSessionsOut', NULL, NULL, 'You have an active session! You can´t create another one!', '0', 0, '0', 'Tiene una sesión activa! No puede crear otra!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.message', NULL, NULL, 'Please enter your user name and password', '0', 0, '0', 'Por favor ingresar su nombre de usuario y contraseña');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.password', NULL, NULL, 'Password', '0', 0, '0', 'Contraseña');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.userDisabled', NULL, NULL, 'User is disabled', '0', 0, '0', 'Usuario esta inactivo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.userEnabled', NULL, NULL, 'User is enabled', '0', 0, '0', 'Usuario esta activo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('login.username', NULL, NULL, 'User name', '0', 0, '0', 'Nombre de usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('logindate', NULL, NULL, 'Login date', '0', 0, '0', 'Fecha ingreso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('logout', NULL, NULL, 'Logout', '0', 0, '0', 'Salir');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('logoutdate', NULL, NULL, 'Logout date', '0', 0, '0', 'Fecha salida');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('logouturl', NULL, NULL, 'Logout url', '0', 0, '0', 'URL salida');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('messageKey', NULL, NULL, 'Message key', '0', 0, '0', 'Código mensaje');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('modifiedBy', NULL, NULL, 'Modified by', '0', 0, '0', 'Modificado por');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('newResult', NULL, NULL, 'New result', '0', 0, '0', 'Nuevo resultado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('noResults', NULL, NULL, 'There are no results', '0', 0, '0', 'No hay registros!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('not', NULL, NULL, 'Notification', '0', 0, '0', 'Notificación');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('notenabled', NULL, NULL, 'Disabled', '0', 0, '0', 'Deshabilitado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('notfound', NULL, NULL, 'Not found', '0', 0, '0', 'No encontrado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('notfoundmessage', NULL, NULL, 'Sorry, the page you\'re looking for can\'t be found', '0', 0, '0', 'Lo sentimos, la página que solicitó no pudo ser encontrada.');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('notlocked', NULL, NULL, 'Unlocked', '0', 0, '0', 'Desbloqueado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ok', NULL, NULL, 'Accept', '0', 0, '0', 'Aceptar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('opcionesCatalogo', NULL, NULL, 'Responses in this catalogue', '0', 0, '0', 'Respuestas en este catálogo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('options', NULL, NULL, 'Options', '0', 0, '0', 'Opciones');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('order', NULL, NULL, 'Order', '0', 0, '0', 'Ordenamiento');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('parameter', NULL, NULL, 'parameter', '0', 0, '0', 'Parámetro');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pasive', NULL, NULL, 'disabled', '0', 0, '0', 'De baja');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pasivo', NULL, NULL, 'canceled', '0', 0, '0', 'Anulado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pass.updated', NULL, NULL, 'Password updated', '0', 0, '0', 'Su contraseña ha sido actualizada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('password.repeat', NULL, NULL, 'Repeat Password', '0', 0, '0', 'Repita la contraseña');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('Pattern.password.format', NULL, NULL, 'At least 8 characters combining uppercase, lowercase, numbers and special characters', '0', 0, '0', 'Al menos 8 caracteres combinando mayúsculas, minúsculas, numeros y caracteres especiales');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('please.enter', NULL, NULL, 'Please enter', '0', 0, '0', 'Favor ingresar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('process.errors', NULL, NULL, 'errors have occurred in the process ', '0', 0, '0', 'Han ocurrido errores en el proceso!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('process.success', NULL, NULL, 'the process has been successfully completed', '0', 0, '0', 'El proceso se ha completado exitosamente!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('process.wait', NULL, NULL, 'please wait', '0', 0, '0', 'Por favor espere..');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('profile', NULL, NULL, 'Profile', '0', 0, '0', 'Perfil');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('resetPassword', NULL, NULL, 'New password sent by e-mail', '0', 0, '0', 'Enviar nueva contraseña por correo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('rolAdded', NULL, NULL, 'Added role', '0', 0, '0', 'Rol agregado!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('rolAll', NULL, NULL, 'all roles are already added', '0', 0, '0', 'Todos los roles ya están agregados!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('rolDisabled', NULL, NULL, 'role is inactive', '0', 0, '0', 'Rol esta inactivo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('rolEnabled', NULL, NULL, 'role is active', '0', 0, '0', 'Rol esta activo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_ADMIN', NULL, NULL, 'administrator ', '0', 0, '0', 'Administrador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_PASSWORD', NULL, NULL, 'Change password', '0', 0, '0', 'Cambio de contraseña');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_REVIEW', NULL, NULL, 'View Data', '0', 0, '0', 'Visualizar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_SPRAY', NULL, NULL, 'Spray', '0', 0, '0', 'Rociador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_SUPER', NULL, NULL, 'Supervisor', '0', 0, '0', 'Supervisor');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ROLE_CENSUS', NULL, NULL, 'Census', '0', 0, '0', 'Censo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('save', NULL, NULL, 'save', '0', 0, '0', 'Guardar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('search', NULL, NULL, 'search', '0', 0, '0', 'Buscar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('searchResult', NULL, NULL, 'search result', '0', 0, '0', 'Buscar resultado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('seccatalogs', NULL, NULL, 'answers/response', '0', 0, '0', 'Respuestas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('seccatalogsform', NULL, NULL, 'Answer/response management', '0', 0, '0', 'Gestión de respuestas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('secondEntry', NULL, NULL, 'second entry', '0', 0, '0', 'Segunda entrada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('seconds', NULL, NULL, 'seconds', '0', 0, '0', 'segundos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('select', NULL, NULL, 'select', '0', 0, '0', 'Seleccionar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('selected', NULL, NULL, 'selected', '0', 0, '0', 'Seleccionados');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('session', NULL, NULL, 'session ID', '0', 0, '0', 'Id de sesion');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('session.expiring', NULL, NULL, 'your session is about to expire', '0', 0, '0', 'Su sesión está a punto de expirar!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('session.expiring.confirm', NULL, NULL, 'do you want to continue with your session?', '0', 0, '0', 'Quiere continuar con su sesión?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('session.expiring.time', NULL, NULL, 'your session will close in…', '0', 0, '0', 'Su sesión se cerrará en');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('session.keep', NULL, NULL, 'keep session', '0', 0, '0', 'Mantener sesión');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('spanish', NULL, NULL, 'spanish', '0', 0, '0', 'Español');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('title', NULL, NULL, 'VCA', '0', 0, '0', 'ACV');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('translation', NULL, NULL, 'translation', '0', 0, '0', 'Traducción');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('translations', NULL, NULL, 'translation of messages', '0', 0, '0', 'Traducción de mensajes');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('unlock', NULL, NULL, 'unlock', '0', 0, '0', 'Desbloquear');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('user.created', NULL, NULL, 'user created', '0', 0, '0', 'Usuario creado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('user.updated', NULL, NULL, 'user updated', '0', 0, '0', 'Usuario actualizado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usercred', NULL, NULL, 'password expired', '0', 0, '0', 'Contraseña vencida');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('userdesc', NULL, NULL, 'user description', '0', 0, '0', 'Descripción');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('useremail', NULL, NULL, 'user email', '0', 0, '0', 'Correo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('userexp', NULL, NULL, 'expired account', '0', 0, '0', 'Cuenta vencida');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('userlock', NULL, NULL, 'locked', '0', 0, '0', 'Bloqueado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('username', NULL, NULL, 'username', '0', 0, '0', 'Usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('userroles', NULL, NULL, 'roles', '0', 0, '0', 'Roles');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('users', NULL, NULL, 'users', '0', 0, '0', 'Usuarios');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usuarioAdded', NULL, NULL, 'user added', '0', 0, '0', 'Usuario agregado!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usuarioAll', NULL, NULL, 'all users are already added', '0', 0, '0', 'Todos los usuarios ya están agregados!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usuarioDisabled', NULL, NULL, 'user is inactivated', '0', 0, '0', 'Usuario está inactivo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usuarioEnabled', NULL, NULL, 'user is activated', '0', 0, '0', 'Usuario está activo!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('value', NULL, NULL, 'value', '0', 0, '0', 'Valor');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('welcome', NULL, NULL, 'welcome', '0', 0, '0', 'Bienvenido ');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('areas', NULL, NULL, 'Areas', '0', 0, '0', 'Areas de salud');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('districts', NULL, NULL, 'Districts', '0', 0, '0', 'Distritos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('localities', NULL, NULL, 'Localities', '0', 0, '0', 'Localidades');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('area', NULL, NULL, 'Area', '0', 0, '0', 'Area de salud');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('district', NULL, NULL, 'District', '0', 0, '0', 'Distrito');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('locality', NULL, NULL, 'Locality', '0', 0, '0', 'Localidad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Area', NULL, NULL, 'Area', '0', 0, '0', 'Area');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Distrito', NULL, NULL, 'District', '0', 0, '0', 'Distrito');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Localidad', NULL, NULL, 'Locality', '0', 0, '0', 'Localidad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Household', NULL, NULL, 'House', '0', 0, '0', 'Vivienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ident', NULL, NULL, 'Identifier', '0', 0, '0', 'Identificador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('code', NULL, NULL, 'Code', '0', 0, '0', 'Código');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('name', NULL, NULL, 'Name', '0', 0, '0', 'Nombre');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('location', NULL, NULL, 'Location', '0', 0, '0', 'Ubicación');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('latitude', NULL, NULL, 'Latitude', '0', 0, '0', 'Latitud');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('longitude', NULL, NULL, 'Longitude', '0', 0, '0', 'Longitud');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('population', NULL, NULL, 'Population', '0', 0, '0', 'Población');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('obs', NULL, NULL, 'Notes', '0', 0, '0', 'Observaciones');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pattern', NULL, NULL, 'Pattern', '0', 0, '0', 'Patrón');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('orgunit', NULL, NULL, 'Org Units', '0', 0, '0', 'Unidades Organizativas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('sysopts', NULL, NULL, 'System options', '0', 0, '0', 'Opciones sistema');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('resources', NULL, NULL, 'Human resources', '0', 0, '0', 'Recursos humanos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('parameters', NULL, NULL, 'Parameters', '0', 0, '0', 'Parámetros');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('locselect', NULL, NULL, 'Click on the map or drag the marker', '0', 0, '0', 'Hacer click en el mapa o arrastrar el marcador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('505', NULL, NULL, 'Something´s wrong!', '0', 0, '0', 'Ha ocurrido un error!');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('userlocs', NULL, NULL, 'User localities', '0', 0, '0', 'Localidades del usuario');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.relationships.UsuarioLocalidad', NULL, NULL, 'Locality', '0', 0, '0', 'Localidad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('censustaker', NULL, NULL, 'Census taker', '0', 0, '0', 'Censador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('sprayer', NULL, NULL, 'Sprayer', '0', 0, '0', 'Rociador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supervisor', NULL, NULL, 'Supervisor', '0', 0, '0', 'Supervisor');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('brigades', NULL, NULL, 'Brigades', '0', 0, '0', 'Brigada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Censador', NULL, NULL, 'Census taker', '0', 0, '0', 'Censador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Supervisor', NULL, NULL, 'Supervisor', '0', 0, '0', 'Supervisor');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Rociador', NULL, NULL, 'Sprayer', '0', 0, '0', 'Rociador');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Brigada', NULL, NULL, 'Brigade', '0', 0, '0', 'Brigada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Visit', NULL, NULL, 'Visit', '0', 0, '0', 'Visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Target', NULL, NULL, 'Target', '0', 0, '0', 'Objetivo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.IrsSeason', NULL, NULL, 'Irs Season', '0', 0, '0', 'Temporada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.irs.Supervision', NULL, NULL, 'Supervision', '0', 0, '0', 'Supervisión');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('map', NULL, NULL, 'Map', '0', 0, '0', 'Mapa');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('list', NULL, NULL, 'List', '0', 0, '0', 'Lista');
//Catalogos
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_SINO', NULL, NULL, 'Catalogue yes/no', '1', 0, '0', 'Catalogo Si No');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_SINO_NO', '0', 'CAT_SINO', 'No', '0', 2, '0', 'No');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_SINO_SI', '1', 'CAT_SINO', 'Yes', '0', 1, '0', 'Si');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_HAB', NULL, NULL, 'Catalogue inhabited', '1', 0, '0', 'Catalogo Habitada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_HAB_NO', '0', 'CAT_HAB', 'No', '0', 2, '0', 'No');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_HAB_SI', '1', 'CAT_HAB', 'Yes', '0', 1, '0', 'Si');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_HAB_NA', '9', 'CAT_HAB', 'Closed', '0', 3, '0', 'Cerrada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT', NULL, NULL, 'Catalogue materials', '1', 0, '0', 'Catalogo Materiales');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_01', '01', 'CAT_MAT', '', '0', 1, '0', 'Bloque Rústico');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_02', '02', 'CAT_MAT', '', '0', 2, '0', 'Bloque Repellado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_03', '03', 'CAT_MAT', '', '0', 3, '0', 'Madera');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_04', '04', 'CAT_MAT', '', '0', 4, '0', 'Lámina');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_05', '05', 'CAT_MAT', '', '0', 5, '0', 'Plástico');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_MAT_06', '06', 'CAT_MAT', '', '0', 6, '0', 'Otro');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RNR', NULL, NULL, 'Catalogue non sprayable', '1', 0, '0', 'Catalogo Razones no Rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RNR_01', '01', 'CAT_RNR', '', '0', 1, '0', 'Farmacia');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RNR_02', '02', 'CAT_RNR', '', '0', 2, '0', 'Tienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RNR_03', '03', 'CAT_RNR', '', '0', 3, '0', 'Bodega de alimentos');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS', NULL, NULL, 'Catalogue status house', '1', 0, '0', 'Catalogo Estado de la vivienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_01', 'SPRTOT', 'CAT_STATUS', 'Sprayed', '0', 1, '0', 'Rociada total');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_02', 'SPRPAR', 'CAT_STATUS', 'Partial Sprayed', '0', 2, '0', 'Rociada parcial');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_03', 'RELUCT', 'CAT_STATUS', 'Reluctant', '0', 3, '0', 'Renuente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_04', 'CLOSED', 'CAT_STATUS', 'Closed', '0', 4, '0', 'Cerrada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_05', 'NOTIFI', 'CAT_STATUS', 'Notified', '0', 5, '0', 'Con preaviso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_06', 'NONOTI', 'CAT_STATUS', 'Unnotified', '0', 6, '0', 'Sin preaviso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_STATUS_07', 'NOTVIS', 'CAT_STATUS', 'Never visited', '0', 7, '0', 'Nunca visitada');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_TYPE', NULL, NULL, 'Catalogue visit type', '1', 0, '0', 'Catalogo Tipo de visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_TYPE_01', 'NOTICE', 'CAT_VIS_TYPE', 'Notice', '0', 1, '0', 'Pre aviso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_TYPE_02', 'SPRAY', 'CAT_VIS_TYPE', 'Spray', '0', 2, '0', 'Rociado');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_CAT', NULL, NULL, 'Catalogue visit cat', '1', 0, '0', 'Catalogo categoria de visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_CAT_01', '1', 'CAT_VIS_CAT', 'First', '0', 1, '0', 'Inicial');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_VIS_CAT_02', '2', 'CAT_VIS_CAT', 'Follow up', '0', 2, '0', 'Seguimiento');


INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_NO_VISIT', NULL, NULL, 'Catalogue reasons no visit', '1', 0, '0', 'Catalogo razones no visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_NO_VISIT_01', 'CLOSED', 'CAT_NO_VISIT', 'Closed', '0', 1, '0', 'Cerrada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_NO_VISIT_02', 'RELUCT', 'CAT_NO_VISIT', 'Reluctant', '0', 2, '0', 'Renuente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_NO_VISIT_03', 'DESTRO', 'CAT_NO_VISIT', 'Destroyed', '0', 3, '0', 'Destruída');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_NO_VISIT_04', 'OTHER', 'CAT_NO_VISIT', 'Other', '0', 4, '0', 'Otras razones (especifique)');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RELUCTANT', NULL, NULL, 'Catalogue reasons reluctant', '1', 0, '0', 'Catalogo renuente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RELUCTANT_01', 'PREGNANCY', 'CAT_RELUCTANT', 'Pregnancy', '0', 1, '0', 'Mujer embarazada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RELUCTANT_02', 'NEWBORN', 'CAT_RELUCTANT', 'New Born', '0', 2, '0', 'Recien nacido en casa');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RELUCTANT_03', 'ILLNESS', 'CAT_RELUCTANT', 'Illness', '0', 3, '0', 'Persona enferma');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('CAT_RELUCTANT_04', 'OTHER', 'CAT_RELUCTANT', 'Other', '0', 4, '0', 'Otras razones (especifique)');

//Censo
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('census', NULL, NULL, 'Census', '0', 0, '0', 'Censo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('codeHouse', NULL, NULL, 'House id', '0', 0, '0', 'Número de Vivienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('censusDate', NULL, NULL, 'Census date', '0', 0, '0', 'Día del censo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('inhabited', NULL, NULL, 'Inhabited', '0', 0, '0', 'Vivienda Habitada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ownerName', NULL, NULL, 'Owner Name', '0', 0, '0', 'Jefe de Familia');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('habitants', NULL, NULL, 'Habitants', '0', 0, '0', 'Número de habitantes');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('material', NULL, NULL, 'Material', '0', 0, '0', 'Materiales de la estructura principal (paredes)');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('rooms', NULL, NULL, 'Rooms', '0', 0, '0', 'Número de cuartos de la vivienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('sprRooms', NULL, NULL, '', '0', 0, '0', 'Número de Cuartos Rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('noSprooms', NULL, NULL, '', '0', 0, '0', 'Número de Cuartos No rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('noSproomsReasons', NULL, NULL, '', '0', 0, '0', 'Razones no rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('personasCharlas', NULL, NULL, '', '0', 0, '0', 'Numero de personas se imparte charla');


//Dashboard censo
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivday', NULL, NULL, '', '0', 0, '0', 'Viviendas censadas por día');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivtot', NULL, NULL, '', '0', 0, '0', 'Viviendas totales');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivact', NULL, NULL, '', '0', 0, '0', 'Viviendas activas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivnoact', NULL, NULL, '', '0', 0, '0', 'Viviendas inactivas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('viewcensus', NULL, NULL, '', '0', 0, '0', 'Revisar el censo');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('cuartostot', NULL, NULL, '', '0', 0, '0', 'Total cuartos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('cuartosroc', NULL, NULL, '', '0', 0, '0', 'Cuartos rociables');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('filters', NULL, NULL, 'Filters', '0', 0, '0', 'Filtros');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('settings', NULL, NULL, 'Settings', '0', 0, '0', 'Configuración');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('update', NULL, NULL, 'Update', '0', 0, '0', 'Actualizar');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('foci', NULL, NULL, 'Foci', '0', 0, '0', 'Focos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.Foco', NULL, NULL, 'Foci', '0', 0, '0', 'Foco');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('class org.clintonhealthaccess.vca.domain.relationships.FocoLocalidad', NULL, NULL, 'Localidad', '0', 0, '0', 'Localidad en el Foco');


INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('tipoou', NULL, NULL, 'Org unit', '0', 0, '0', 'Unidad Organizativa');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivou', NULL, NULL, '', '0', 0, '0', 'Viviendas censadas por unidad organizativa');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('ou', NULL, NULL, '', '0', 0, '0', 'unidad organizativa');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivhab', NULL, NULL, '', '0', 0, '0', 'Viviendas habitadas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivdeshab', NULL, NULL, '', '0', 0, '0', 'Viviendas no habitadas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivcerrada', NULL, NULL, '', '0', 0, '0', 'Viviendas cerradas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivcuartos', NULL, NULL, '', '0', 0, '0', 'Total de cuartos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivcuartosroc', NULL, NULL, '', '0', 0, '0', 'Cuartos rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivcuartosnoroc', NULL, NULL, '', '0', 0, '0', 'Cuartos no rociables');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('vivtothab', NULL, NULL, '', '0', 0, '0', 'Total habitantes');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totvisit', NULL, NULL, '', '0', 0, '0', 'Total visitas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totexito', NULL, NULL, '', '0', 0, '0', 'Visitas completas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totfracaso', NULL, NULL, '', '0', 0, '0', 'Visitas fallidas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totpreav', NULL, NULL, '', '0', 0, '0', 'Visitas preaviso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totrociado', NULL, NULL, '', '0', 0, '0', 'Visitas rociado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totiniciales', NULL, NULL, '', '0', 0, '0', 'Visitas iniciales');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totseg', NULL, NULL, '', '0', 0, '0', 'Visitas seguimiento');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totrociados', NULL, NULL, '', '0', 0, '0', 'Cuartos rociados');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totcargas', NULL, NULL, '', '0', 0, '0', 'Total cargas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('totcharlas', NULL, NULL, '', '0', 0, '0', 'Habitantes charlas');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('irs', NULL, NULL, 'IRS', '0', 0, '0', 'RRI');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('dashboard', NULL, NULL, 'Dashboard', '0', 0, '0', 'Tablero');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('spray', NULL, NULL, 'Sprays', '0', 0, '0', 'Rociados');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supervision', NULL, NULL, 'Supervision', '0', 0, '0', 'Supervisión');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('season', NULL, NULL, 'Seasons', '0', 0, '0', 'Temporadas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('visits', NULL, NULL, 'Visits', '0', 0, '0', 'Visitas');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('startDate', NULL, NULL, 'Start date', '0', 0, '0', 'Fecha de inicio');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('endDate', NULL, NULL, 'End date', '0', 0, '0', 'Fecha de fin');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('numberDays', NULL, NULL, 'Number of days', '0', 0, '0', 'Número de días');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('planning', NULL, NULL, 'Planning', '0', 0, '0', 'Planificación');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('targets', NULL, NULL, 'Targets', '0', 0, '0', 'Meta');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('sprayStatus', NULL, NULL, 'Status', '0', 0, '0', 'Estado');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('visitDate', NULL, NULL, 'visit Date', '0', 0, '0', 'Fecha de visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('visit', NULL, NULL, 'Visita', '0', 0, '0', 'Visita');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('activity', NULL, NULL, 'Activity', '0', 0, '0', 'Actividad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('compVisit', NULL, NULL, 'compete Visit', '0', 0, '0', 'Se realiza la actividad?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reasonNoVisit', NULL, NULL, 'reason No Visit', '0', 0, '0', 'Porque se no realiza la actividad?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reasonNoVisitOther', NULL, NULL, 'reason No Visit Other', '0', 0, '0', 'Otra razon');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reasonReluctant', NULL, NULL, 'reason Reluctant', '0', 0, '0', 'Motivo renuente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reasonReluctantOther', NULL, NULL, 'reason Reluctant Other', '0', 0, '0', 'Otro motivo renuente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('sprayedRooms', NULL, NULL, 'sprayed Rooms', '0', 0, '0', 'Cuartos rociados');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('numCharges', NULL, NULL, 'num Charges', '0', 0, '0', 'Numero de cargas utilizadas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reasonIncomplete', NULL, NULL, 'reason Incomplete', '0', 0, '0', 'Porque no se rociaron todos los cuartos?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supervised', NULL, NULL, 'supervised', '0', 0, '0', 'El rociado fue supervisado en esta vivienda?');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supervisionDate', NULL, NULL, 'supervision Date', '0', 0, '0', 'Fecha de supervisión');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('usoEqProt', NULL, NULL, 'usoEqProt', '0', 0, '0', 'El equpo de protección está bien llevado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('eqProtBien', NULL, NULL, 'eqProtBien', '0', 0, '0', 'El equipo de protección está en buen estado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('numIden', NULL, NULL, 'numIden', '0', 0, '0', 'Pone su número de identificación y lo hace correctamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('aguaOp', NULL, NULL, 'aguaOp', '0', 0, '0', 'Solicita agua oportunamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('prepViv', NULL, NULL, 'prepViv', '0', 0, '0', 'Comprueba la preparación de la vivienda');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('coopPrepViv', NULL, NULL, 'coopPrepViv', '0', 0, '0', 'Coopera en la preparación de la vivienda');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('aguaAdec', NULL, NULL, 'aguaAdec', '0', 0, '0', 'Aplica la cantidad adecuada de agua');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('mezclaPrep', NULL, NULL, 'mezclaPrep', '0', 0, '0', 'Prepara bien la mezcla');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('agitaBomba', NULL, NULL, 'agitaBomba', '0', 0, '0', 'Agita correctamente la bomba');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('bombaCerrada', NULL, NULL, 'bombaCerrada', '0', 0, '0', 'La bomba está cerrada correctamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('bombaPresion', NULL, NULL, 'bombaPresion', '0', 0, '0', 'La bomba tiene la presión correcta (55psi)');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('compruebaBomba', NULL, NULL, 'compruebaBomba', '0', 0, '0', 'Comprueba su funcionamiento antes de rociar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('colocApropiada', NULL, NULL, 'colocApropiada', '0', 0, '0', 'Se coloca adecuadamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('distApropiada', NULL, NULL, 'distApropiada', '0', 0, '0', 'Calcula la distancia adecuada');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('distBoquilla', NULL, NULL, 'distBoquilla', '0', 0, '0', 'Mantiene la distancia de la boquilla al momento de rociar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pasoFrente', NULL, NULL, 'pasoFrente', '0', 0, '0', 'Da un paso al frente en las superficies altas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('mantRitmo', NULL, NULL, 'mantRitmo', '0', 0, '0', 'Mantiene el ritmo al rociar');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('metConteo', NULL, NULL, 'metConteo', '0', 0, '0', 'Utiliza el método del conteo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('velocSuperficies', NULL, NULL, 'velocSuperficies', '0', 0, '0', 'Mantiene volocidad adecuada en las superficies');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supFajas', NULL, NULL, 'supFajas', '0', 0, '0', 'Superpone las fajas correctamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('pasosLaterales', NULL, NULL, 'pasosLaterales', '0', 0, '0', 'Da los pasos laterales de 70 cm aproximadamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('salvarObstaculos', NULL, NULL, 'salvarObstaculos', '0', 0, '0', 'Tiene habilidad para salvar obstáculos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('bienRociado', NULL, NULL, 'bienRociado', '0', 0, '0', 'Rocía bien las superficies');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('supInvertidas', NULL, NULL, 'supInvertidas', '0', 0, '0', 'Rocía las superficies invertidas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('objPiso', NULL, NULL, 'objPiso', '0', 0, '0', 'Rocía objetos en el piso');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('reportaConsumoAprop', NULL, NULL, 'reportaConsumoAprop', '0', 0, '0', 'La cantidad de cargas reportadas corresponde a la cantidad de producto utilizado');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('transEqAprop', NULL, NULL, 'transEqAprop', '0', 0, '0', 'Transporta el equipo correctamente');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('eqCompleto', NULL, NULL, 'eqCompleto', '0', 0, '0', 'Lleva equipo completo');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('cuidaMatEq', NULL, NULL, 'cuidaMatEq', '0', 0, '0', 'Cuida sus materiales y equipos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('buenAspPersonal', NULL, NULL, 'buenAspPersonal', '0', 0, '0', 'Su aspecto personal es bueno');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('cumpleInstrucciones', NULL, NULL, 'cumpleInstrucciones', '0', 0, '0', 'Cumple con las instrucciones que recibe');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('aceptaSuperv', NULL, NULL, 'aceptaSuperv', '0', 0, '0', 'Acepta la supervisión');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('respetuoso', NULL, NULL, 'respetuoso', '0', 0, '0', 'Es respetuoso con sus compañeros, superiores y habitantes de las viviendas');

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('mezcla', NULL, NULL, 'mezcla', '0', 0, '0', 'Mezcla');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('seguridad', NULL, NULL, 'Seguridad', '0', 0, '0', 'Seguridad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('organizacion', NULL, NULL, 'Organizacion', '0', 0, '0', 'Organización');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('velocidad', NULL, NULL, 'Velocidad', '0', 0, '0', 'Velocidad');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('fajas', NULL, NULL, 'Fajas', '0', 0, '0', 'Fajas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('consumo', NULL, NULL, 'Consumo de insecticidas', '0', 0, '0', 'Consumo de insecticidas');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('otros', NULL, NULL, 'Otros aspectos', '0', 0, '0', 'Otros aspectos');
INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('conducta', NULL, NULL, 'Conducta personal', '0', 0, '0', 'Conducta personal');


//After

INSERT INTO `messages` (`messageKey`, `catKey`, `catRoot`, `en`, `isCat`, `orden`, `catPasive`, `es`) VALUES ('help', NULL, NULL, 'Help', '0', 0, '0', 'Ayuda');




